name: Build Angular App

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force
        working-directory: frontend-angular

      - name: Run linter
        run: npm run lint
        working-directory: frontend-angular

      - name: Build Angular app
        run: npm run build
        working-directory: frontend-angular

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build-artifacts
          path: frontend-angular/dist/

  build-macos:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force
        working-directory: frontend-angular

      - name: Run linter
        run: npm run lint
        working-directory: frontend-angular

      - name: Build Angular app
        run: npm run build
        working-directory: frontend-angular

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build-artifacts
          path: frontend-angular/dist/
